/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.ExcepcionJuego;
import Juego.BBDDJuego;
import Juego.Jugador;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class VentanaIniciarSesion extends javax.swing.JFrame {
    
    static Jugador jugadorReg;
    private static boolean inicioSes;

    /**
     * Creates new form IniciarSesion
     */
    public VentanaIniciarSesion() {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
        DNIInicioSesion.setToolTipText("00000000A");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DNIInicioSesion = new javax.swing.JTextField();
        BotonSiguiente = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INICIAR SESIÓN");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Introduce tu DNI:");

        DNIInicioSesion.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        DNIInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        DNIInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIInicioSesionActionPerformed(evt);
            }
        });

        BotonSiguiente.setBackground(new java.awt.Color(102, 102, 102));
        BotonSiguiente.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        BotonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BotonSiguiente.setText("SIGUIENTE");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        BotonAtras.setBackground(new java.awt.Color(102, 102, 102));
        BotonAtras.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        BotonAtras.setForeground(new java.awt.Color(255, 255, 255));
        BotonAtras.setText("ATRÁS");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(BotonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DNIInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DNIInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isInicioSes() {
        return inicioSes;
    }
    
    public void setInicioSes(boolean inicioSes) {
        this.inicioSes = inicioSes;
    }
    
    private void DNIInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNIInicioSesionActionPerformed

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        // TODO add your handling code here:
        new VentanaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        // TODO add your handling code here:
        
        try {
            BBDDJuego.cargarDatos();
            jugadorReg = BBDDJuego.jugadoresR.get(DNIInicioSesion.getText());
            if (DNIInicioSesion.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "ERROR: No ha introducido su DNI.", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else if (jugadorReg == null) {
                throw new ExcepcionJuego(ExcepcionJuego.USUARIO_NO_EXISTE);
            } else if (DNIInicioSesion.getText().equals(BBDDJuego.jugadoresR.get(DNIInicioSesion.getText()).getDNI())) { //si existe ese usuario
                this.setInicioSes(true);
                new VentanaDificultad().setVisible(true);
                dispose();
            }
        } catch (ExcepcionJuego ej) {
            JOptionPane.showMessageDialog(this, "Error: " + ej.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JTextField DNIInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
