/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Juego.Jugador;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import Juego.BBDDJuego;

/**
 *
 * @author Alvaro
 */
public class VentanaRegistro extends javax.swing.JFrame {

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    static Jugador jugadorAc;
    private static boolean inicioSes;

    /**
     * Creates new form Registro
     */
    public VentanaRegistro() {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
        this.botonSiguiente.setVisible(false);
        nombreRegistro.setToolTipText("María García");
        DNIRegistro.setToolTipText("00000000A");

    }

    public static boolean isInicioSes() {
        return inicioSes;
    }

    public void setInicioSes(boolean inicioSes) {
        this.inicioSes = inicioSes;
    }

    public static String fechaActual() {
        //Inicializo una variable llamada Date
        Date fecha = new Date();
        //Le digo en que formato quiero que este, que sera dia, mes y año
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        //Me retorna un valor que es la fecha acual
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DNIRegistro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonRegistrarUs = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        botonVolverInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        nombreLabel.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Introduce tu nombre:");

        nombreRegistro.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        nombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRegistroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Introduce tu DNI:");

        DNIRegistro.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        DNIRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIRegistroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO");

        botonRegistrarUs.setBackground(new java.awt.Color(102, 102, 102));
        botonRegistrarUs.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        botonRegistrarUs.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarUs.setText("REGISTRAR");
        botonRegistrarUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsActionPerformed(evt);
            }
        });

        botonSiguiente.setBackground(new java.awt.Color(102, 102, 102));
        botonSiguiente.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        botonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        botonSiguiente.setText("SIGUIENTE");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        botonVolverInicio.setBackground(new java.awt.Color(102, 102, 102));
        botonVolverInicio.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        botonVolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        botonVolverInicio.setText("ATRÁS");
        botonVolverInicio.setMaximumSize(new java.awt.Dimension(109, 33));
        botonVolverInicio.setMinimumSize(new java.awt.Dimension(109, 33));
        botonVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DNIRegistro)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(botonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonRegistrarUs, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNIRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrarUs, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInicioActionPerformed
        // TODO add your handling code here:
        new VentanaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverInicioActionPerformed

    private void botonRegistrarUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsActionPerformed

        if (this.nombreRegistro.getText().equals("") || this.DNIRegistro.getText().equals("")) { //Si los espacios a rellenar para registrarse estan en blanco
            JOptionPane.showMessageDialog(this, "ERROR: No puede dejar campos en blanco.", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            String nombre = this.nombreRegistro.getText();
            String DNI = this.DNIRegistro.getText();
            LocalDate fechaAct = LocalDate.now();
            LocalDate fechaReg = LocalDate.parse(fechaAct.format(dtf), dtf);
            Jugador jugadorNuevo = new Jugador(nombre, DNI, fechaReg, 0);
            this.jugadorAc = jugadorNuevo;
            BBDDJuego.altaJugador(jugadorNuevo);
            BBDDJuego.guardarDatos();
            this.botonSiguiente.setVisible(true);
        } catch (NumberFormatException nfe) {//Metodo que utilizaremos para capturar los errores por formato
            System.out.println(nfe.toString());
            JOptionPane.showMessageDialog(this, "ERROR: Error de formato numérico: " + nfe.toString(), "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {//Método para capturar cualquier posible error
            JOptionPane.showMessageDialog(this, "ERROR: " + e.toString(), "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarUsActionPerformed


    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        
        this.setInicioSes(true);
        new VentanaDificultad().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void nombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRegistroActionPerformed

    }//GEN-LAST:event_nombreRegistroActionPerformed

    private void DNIRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIRegistroActionPerformed

    }//GEN-LAST:event_DNIRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNIRegistro;
    private javax.swing.JButton botonRegistrarUs;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton botonVolverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreRegistro;
    // End of variables declaration//GEN-END:variables
}
